### ISSUE TITLE
Not compatible with react@17.0.2

### ISSUE THREAD

**Issue by eugeneford** [teamgantt/react-auto-translate#54]
I receive the following error while trying to install the package with react@17.0.2

<img width="794" alt="image" src="https://user-images.githubusercontent.com/16384615/164269479-83032ba9-89ef-471a-af8c-9dc11590d786.png">

**Comment by anticol** [comment]
Hey @eugeneford did you resolve this?

**Comment by eugeneford** [comment]
@anticol, nope. I had to make my own implementation.

**Comment by johncorrelli** [comment]
@eugeneford and @anticol this should be resolved by #57

**Comment by RichardLindhout** [comment]
Not released on NPM so still relevant for people who are upgrading React :)
